spring.application.name=school-management


spring.datasource.url=jdbc:mysql://localhost:3306/school_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent



management.endpoints.web.exposure.include=*


server.port=10000
